# Generated by Django 5.1.7 on 2025-05-12 12:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NycSubwayStations',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('objectid', models.IntegerField()),
                ('id', models.FloatField()),
                ('name', models.CharField(max_length=31)),
                ('alt_name', models.CharField(max_length=38, null=True)),
                ('cross_st', models.CharField(max_length=27, null=True)),
                ('long_name', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=50)),
                ('borough', models.CharField(max_length=15)),
                ('nghbhd', models.CharField(max_length=30, null=True)),
                ('routes', models.CharField(max_length=20)),
                ('transfers', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=30)),
                ('express', models.CharField(max_length=10, null=True)),
                ('closed', models.CharField(max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26918)),
            ],
            options={
                'db_table': 'nyc_subway_stations',
            },
        ),
    ]
