# Generated by Django 5.1.7 on 2025-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NycCensusSociodata',
            fields=[
                ('tractid', models.CharField(primary_key=True, serialize=False)),
                ('transit_total', models.IntegerField()),
                ('transit_private', models.IntegerField()),
                ('transit_public', models.IntegerField()),
                ('transit_walk', models.IntegerField()),
                ('transit_other', models.IntegerField()),
                ('transit_none', models.IntegerField()),
                ('transit_time_mins', models.FloatField()),
                ('family_count', models.IntegerField()),
                ('family_income_median', models.IntegerField()),
                ('family_income_mean', models.IntegerField()),
                ('family_income_aggregate', models.IntegerField()),
                ('edu_total', models.IntegerField()),
                ('edu_no_highschool_dipl', models.IntegerField()),
                ('edu_highschool_dipl', models.IntegerField()),
                ('edu_college_dipl', models.IntegerField()),
                ('edu_graduate_dipl', models.IntegerField()),
            ],
            options={
                'db_table': 'nyc_census_sociodata',
            },
        ),
    ]
