# Generated by Django 5.1.7 on 2025-04-02 12:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NycNeighborhood',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=43)),
                ('boroname', models.CharField(max_length=64)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'nyc_neighborhoods',
            },
        ),
    ]
