# Generated by Django 5.1.7 on 2025-05-12 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NycCensusBlocks',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('blkid', models.CharField(max_length=15)),
                ('popn_total', models.FloatField()),
                ('popn_white', models.FloatField()),
                ('popn_black', models.FloatField()),
                ('popn_nativ', models.FloatField()),
                ('popn_asian', models.FloatField()),
                ('popn_other', models.FloatField()),
                ('boroname', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26918)),
            ],
            options={
                'db_table': 'nyc_census_blocks',
            },
        ),
    ]
