# Generated by Django 5.1.7 on 2025-04-03 07:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NycStreet',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('oneway', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=26918)),
            ],
            options={
                'db_table': 'nyc_streets',
            },
        ),
    ]
